services:
  db:
    image: mysql
    container_name: MYSQLDB
    ports:
      - 3307:3306
    environment:
      - MYSQL_ROOT_PASSWORD=12345
    volumes:
      - mysql-data:/var/lib/mysql
      - ./db-init:/docker-entrypoint-initdb.d

volumes:
  mysql-data: